sudo: required
services:
  - docker

before_install:
  - docker build -t andyylsong/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true andyylsong/react-test npm test -- --coverage

after_success:
  - docker build -t andyylsong/multi-client -f ./client/Dockerfile ./client
  - docker build -t andyylsong/multi-nginx -f ./nginx/Dockerfile ./nginx
  - docker build -t andyylsong/multi-server -f ./server/Dockerfile ./server
  - docker build -t andyylsong/multi-worker -f ./worker/Dockerfile ./worker
  # log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push andyylsong/multi-client
  - docker push andyylsong/multi-nignx
  - docker push andyylsong/multi-server
  - docker push andyylsong/multi-worker

