sudo: required
services:
  - docker

before_install:
  - docker build -t andy/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true andy/react-test npm test -- --coverage

after_success:
  - docker build -t andy/multi-client -f ./client/Dockerfile ./client
  - docker build -t andy/multi-nginx ./nginx
  - docker build -t andy/multi-server ./server
  - docker build -t andy/multi-worker ./worker
  # log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --pasword-stdin
  # push images to docker hub
  - docker push andy/multi-client
  - docker push andy/multi-nignx
  - docker push andy/multi-server
  - docker push andy/multi-worker

